// Prototyping extended expression trees for C#.
//
// bartde - December 2021

// NB: Running these tests can take a *VERY LONG* time because it invokes the C# compiler for every test
//     case in order to obtain an expression tree object. Be patient when running these tests.

// NB: These tests are generated from a list of expressions in the .tt file by invoking the C# compiler at
//     text template processing time by the T4 engine. See TestUtilities for the helper functions that call
//     into the compiler, load the generated assembly, extract the Expression objects through reflection on
//     the generated type, and call DebugView() on those. The resulting DebugView string is emitted in this
//     file as `expected` variables. The original expression is escaped and gets passed ot the GetDebugView
//     helper method to obtain `actual`, which causes the C# compiler to run at test execution time, using
//     the same helper library, thus obtaining the DebugView string again. This serves a number of goals:
//
//       1. At test generation time, a custom Roslyn build can be invoked to test the implicit conversion
//          of a lambda expression to an expression tree, which involves the changes made to support the
//          C# expression library in this solution. Any fatal compiler errors will come out at that time.
//
//       2. Reflection on the properties in the emitted class causes a deferred execution of the factory
//          method calls generated by the Roslyn compiler for the implicit conversion of the lambda to an
//          expression tree. Any exceptions thrown by the factory methods will show up as well during test
//          generation time, allowing issues to be uncovered.
//
//       3. The string literals in the `expected` variables are inspectable by a human to assert that the
//          compiler has indeed generated an expression representation that's homo-iconic to the original
//          expression that was provided in the test.
//
//       4. Any changes to the compiler or the runtime library could cause regressions. Because template
//          processing of the T4 only takes place upon editing the .tt file, the generated test code won't
//          change. As such, any regression can cause test failures which allows to detect any changes to
//          compiler or runtime library behavior.

using Microsoft.VisualStudio.TestTools.UnitTesting;
using static Tests.Microsoft.CodeAnalysis.CSharp.TestUtilities;

namespace Tests.Microsoft.CodeAnalysis.CSharp
{
    [TestClass]
    public partial class CompilerTests_CSharp80_AwaitUsing
    {
        [TestMethod]
        public void CompilerTest_A100_D276()
        {
            // (Expression<Func<IAsyncDisposable, Task>>)(async d =>  { await using (d) ; })
            var actual = GetDebugView(@"(Expression<Func<IAsyncDisposable, Task>>)(async d =>  { await using (d) ; })");
            var expected = @"
<Lambda Type=""System.Func`2[System.IAsyncDisposable,System.Threading.Tasks.Task]"">
  <Parameters>
    <Parameter Type=""System.IAsyncDisposable"" Id=""0"" Name=""d"" />
  </Parameters>
  <Body>
    <Invoke Type=""System.Threading.Tasks.Task"">
      <Expression>
        <CSharpAsyncLambda Type=""System.Func`2[System.IAsyncDisposable,System.Threading.Tasks.Task]"">
          <Parameters>
            <Parameter Type=""System.IAsyncDisposable"" Id=""0"" Name=""d"" />
          </Parameters>
          <Body>
            <CSharpBlock Type=""System.Void"">
              <Statements>
                <CSharpUsing Type=""System.Void"">
                  <AwaitInfo>
                    <StaticAwaitInfo IsCompleted=""Boolean IsCompleted"" GetResult=""Void GetResult()"">
                      <GetAwaiter>
                        <Lambda Type=""System.Func`2[System.Threading.Tasks.ValueTask,System.Runtime.CompilerServices.ValueTaskAwaiter]"">
                          <Parameters>
                            <Parameter Type=""System.Threading.Tasks.ValueTask"" Id=""1"" Name=""p"" />
                          </Parameters>
                          <Body>
                            <Call Type=""System.Runtime.CompilerServices.ValueTaskAwaiter"" Method=""System.Runtime.CompilerServices.ValueTaskAwaiter GetAwaiter()"">
                              <Object>
                                <Parameter Type=""System.Threading.Tasks.ValueTask"" Id=""1"" Name=""p"" />
                              </Object>
                              <Arguments />
                            </Call>
                          </Body>
                        </Lambda>
                      </GetAwaiter>
                    </StaticAwaitInfo>
                  </AwaitInfo>
                  <Resource>
                    <Parameter Type=""System.IAsyncDisposable"" Id=""0"" Name=""d"" />
                  </Resource>
                  <Body>
                    <Block Type=""System.Void"">
                      <Expressions>
                        <Default Type=""System.Void"" />
                      </Expressions>
                    </Block>
                  </Body>
                </CSharpUsing>
              </Statements>
              <ReturnLabel>
                <LabelTarget Type=""System.Void"" Id=""2"" />
              </ReturnLabel>
            </CSharpBlock>
          </Body>
        </CSharpAsyncLambda>
      </Expression>
      <Arguments>
        <Parameter Type=""System.IAsyncDisposable"" Id=""0"" Name=""d"" />
      </Arguments>
    </Invoke>
  </Body>
</Lambda>";
            Assert.AreEqual(expected.TrimStart('\r', '\n'), actual);
            Verify.CompilerTest_A100_D276();
        }

        partial class Review { /* override in .Verify.cs */ public virtual void CompilerTest_A100_D276() => INCONCLUSIVE(); }

        partial class Review
        {
            protected void INCONCLUSIVE() { Assert.Inconclusive(); }
        }

        partial class Reviewed : Review
        {
            private void OK() { }
            private void FAIL(string message = "") { Assert.Fail(message); }
        }

        private readonly Reviewed Verify = new Reviewed();
    }

/*
// NB: The code generated below accepts all tests. *DON'T* just copy/paste this to the .Verify.cs file
//     but review the tests one by one. This output is included in case a minor change is made to debug
//     output produced by DebugView() and all hashes are invalidated. In that case, this output can be
//     copied and pasted into .Verify.cs.

namespace Tests.Microsoft.CodeAnalysis.CSharp
{
    partial class CompilerTests_CSharp80_AwaitUsing
    {
        partial class Reviewed
        {
            public override void CompilerTest_A100_D276() => OK();
        }
    }
}
*/
}
