// Prototyping extended expression trees for C#.
//
// bartde - December 2021

// NB: Running these tests can take a *VERY LONG* time because it invokes the C# compiler for every test
//     case in order to obtain an expression tree object. Be patient when running these tests.

// NB: These tests are generated from a list of expressions in the .tt file by invoking the C# compiler at
//     text template processing time by the T4 engine. See TestUtilities for the helper functions that call
//     into the compiler, load the generated assembly, extract the Expression objects through reflection on
//     the generated type, and call DebugView() on those. The resulting DebugView string is emitted in this
//     file as `expected` variables. The original expression is escaped and gets passed ot the GetDebugView
//     helper method to obtain `actual`, which causes the C# compiler to run at test execution time, using
//     the same helper library, thus obtaining the DebugView string again. This serves a number of goals:
//
//       1. At test generation time, a custom Roslyn build can be invoked to test the implicit conversion
//          of a lambda expression to an expression tree, which involves the changes made to support the
//          C# expression library in this solution. Any fatal compiler errors will come out at that time.
//
//       2. Reflection on the properties in the emitted class causes a deferred execution of the factory
//          method calls generated by the Roslyn compiler for the implicit conversion of the lambda to an
//          expression tree. Any exceptions thrown by the factory methods will show up as well during test
//          generation time, allowing issues to be uncovered.
//
//       3. The string literals in the `expected` variables are inspectable by a human to assert that the
//          compiler has indeed generated an expression representation that's homo-iconic to the original
//          expression that was provided in the test.
//
//       4. Any changes to the compiler or the runtime library could cause regressions. Because template
//          processing of the T4 only takes place upon editing the .tt file, the generated test code won't
//          change. As such, any regression can cause test failures which allows to detect any changes to
//          compiler or runtime library behavior.

using Xunit;
using static Tests.Microsoft.CodeAnalysis.CSharp.TestUtilities;

namespace Tests.Microsoft.CodeAnalysis.CSharp
{
    public partial class CompilerTests_CSharp70_PatternSwitchStatement
    {
        [Fact]
        public void CompilerTest_7FA0_C84E()
        {
            // (Expression<Action<object>>)(o => { switch (o) { case 0: Console.Write('0'); break; case int x when x > 0: Console.Write(x); break; case var t: Console.WriteLine(t); break; } })
            var actual = GetDebugView(@"(Expression<Action<object>>)(o => { switch (o) { case 0: Console.Write('0'); break; case int x when x > 0: Console.Write(x); break; case var t: Console.WriteLine(t); break; } })");
            var expected = @"
<Lambda Type=""System.Action`1[System.Object]"">
  <Parameters>
    <Parameter Type=""System.Object"" Id=""0"" Name=""o"" />
  </Parameters>
  <Body>
    <CSharpBlock Type=""System.Void"">
      <Statements>
        <CSharpSwitch Type=""System.Void"">
          <SwitchValue>
            <Parameter Type=""System.Object"" Id=""0"" Name=""o"" />
          </SwitchValue>
          <Sections>
            <SwitchSection>
              <Labels>
                <SwitchLabel>
                  <Label>
                    <LabelTarget Type=""System.Void"" Id=""1"" Name=""case 0:"" />
                  </Label>
                  <Pattern>
                    <ConstantPattern InputType=""System.Object"" NarrowedType=""System.Int32"">
                      <Constant Type=""System.Int32"" Value=""0"" />
                    </ConstantPattern>
                  </Pattern>
                </SwitchLabel>
              </Labels>
              <Statements>
                <Call Type=""System.Void"" Method=""Void Write(Char)"">
                  <Arguments>
                    <Constant Type=""System.Char"" Value=""0"" />
                  </Arguments>
                </Call>
                <Goto Type=""System.Void"" Kind=""Break"">
                  <Target>
                    <LabelTarget Type=""System.Void"" Id=""2"" />
                  </Target>
                </Goto>
              </Statements>
            </SwitchSection>
            <SwitchSection>
              <Locals>
                <Parameter Type=""System.Int32"" Id=""3"" Name=""x"" />
              </Locals>
              <Labels>
                <SwitchLabel>
                  <Label>
                    <LabelTarget Type=""System.Void"" Id=""4"" Name=""case int x when x &gt; 0:"" />
                  </Label>
                  <Pattern>
                    <DeclarationPattern InputType=""System.Object"" NarrowedType=""System.Int32"" Type=""System.Int32"">
                      <Variable>
                        <Parameter Type=""System.Int32"" Id=""3"" Name=""x"" />
                      </Variable>
                    </DeclarationPattern>
                  </Pattern>
                  <WhenClause>
                    <GreaterThan Type=""System.Boolean"">
                      <Left>
                        <Parameter Type=""System.Int32"" Id=""3"" Name=""x"" />
                      </Left>
                      <Right>
                        <Constant Type=""System.Int32"" Value=""0"" />
                      </Right>
                    </GreaterThan>
                  </WhenClause>
                </SwitchLabel>
              </Labels>
              <Statements>
                <Call Type=""System.Void"" Method=""Void Write(Int32)"">
                  <Arguments>
                    <Parameter Type=""System.Int32"" Id=""3"" Name=""x"" />
                  </Arguments>
                </Call>
                <Goto Type=""System.Void"" Kind=""Break"">
                  <Target>
                    <LabelTarget Type=""System.Void"" Id=""2"" />
                  </Target>
                </Goto>
              </Statements>
            </SwitchSection>
            <SwitchSection>
              <Locals>
                <Parameter Type=""System.Object"" Id=""5"" Name=""t"" />
              </Locals>
              <Labels>
                <SwitchLabel>
                  <Label>
                    <LabelTarget Type=""System.Void"" Id=""6"" Name=""case var t:"" />
                  </Label>
                  <Pattern>
                    <VarPattern InputType=""System.Object"" NarrowedType=""System.Object"">
                      <Variable>
                        <Parameter Type=""System.Object"" Id=""5"" Name=""t"" />
                      </Variable>
                      <Variable>
                        <Parameter Type=""System.Object"" Id=""5"" Name=""t"" />
                      </Variable>
                    </VarPattern>
                  </Pattern>
                </SwitchLabel>
              </Labels>
              <Statements>
                <Call Type=""System.Void"" Method=""Void WriteLine(System.Object)"">
                  <Arguments>
                    <Parameter Type=""System.Object"" Id=""5"" Name=""t"" />
                  </Arguments>
                </Call>
                <Goto Type=""System.Void"" Kind=""Break"">
                  <Target>
                    <LabelTarget Type=""System.Void"" Id=""2"" />
                  </Target>
                </Goto>
              </Statements>
            </SwitchSection>
          </Sections>
          <BreakLabel>
            <LabelTarget Type=""System.Void"" Id=""2"" />
          </BreakLabel>
        </CSharpSwitch>
      </Statements>
      <ReturnLabel>
        <LabelTarget Type=""System.Void"" Id=""7"" />
      </ReturnLabel>
    </CSharpBlock>
  </Body>
</Lambda>";
            Assert.Equal(expected.TrimStart('\r', '\n'), actual);
            Verify.CompilerTest_7FA0_C84E();
        }

        partial class Review { /* override in .Verify.cs */ public virtual void CompilerTest_7FA0_C84E() => INCONCLUSIVE(); }

        partial class Review
        {
            protected void INCONCLUSIVE() { /* Assert.Inconclusive(); */ Assert.Fail("INCONCLUSIVE"); }
        }

        partial class Reviewed : Review
        {
            private void OK() { }
            private void FAIL(string message = "") { Assert.Fail(message); }
        }

        private readonly Reviewed Verify = new Reviewed();
    }

/*
// NB: The code generated below accepts all tests. *DON'T* just copy/paste this to the .Verify.cs file
//     but review the tests one by one. This output is included in case a minor change is made to debug
//     output produced by DebugView() and all hashes are invalidated. In that case, this output can be
//     copied and pasted into .Verify.cs.

namespace Tests.Microsoft.CodeAnalysis.CSharp
{
    partial class CompilerTests_CSharp70_PatternSwitchStatement
    {
        partial class Reviewed
        {
            public override void CompilerTest_7FA0_C84E() => OK();
        }
    }
}
*/
}
